version: "3.8"

services:

    nginx:
        restart: always
        container_name: ${APP_NAME}Nginx
        depends_on:
            - php
        working_dir: /var/www/html
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/data/logs/:/var/log/nginx/
        build:
            context: ./docker/nginx
            args:
                USER: ${DOCKER_USER}
                GROUP: ${DOCKER_USER_GROUP}
                UID: ${DOCKER_USER_ID}
                GID: ${DOCKER_USER_GROUP_ID}
        networks:
            - web
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    php:
        restart: always
        build:
            context: ./docker/php
            args:
                USER: ${DOCKER_USER}
                GROUP: ${DOCKER_USER_GROUP}
                UID: ${DOCKER_USER_ID}
                GID: ${DOCKER_USER_GROUP_ID}
        container_name: ${APP_NAME}Application
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - web

    redis:
        restart: always
        build:
            context: ./docker/redis
        container_name: ${APP_NAME}Redis
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "${REDIS_PORT}:6379"
        command: >
            --requirepass ${REDIS_PASSWORD}
        logging:
            options:
                max-size: "1m"
                max-file: "10"
        networks:
            - web

    supervisor:
        restart: always
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                USER: ${DOCKER_USER}
                GROUP: ${DOCKER_USER_GROUP}
                UID: ${DOCKER_USER_ID}
                GID: ${DOCKER_USER_GROUP_ID}
        container_name: ${APP_NAME}Supervisor
        volumes:
            - ./:/var/www/html/:delegated
        links:
            - redis
        depends_on:
            - redis
        working_dir: /var/www/html
        entrypoint: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
        networks:
            - web

    db:
        build:
            context: ./docker/db
        container_name: ${APP_NAME}Database
        restart: unless-stopped
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: db
        volumes:
            - ./docker/db/data:/var/lib/mysql/
        networks:
            - web

    phpmyadmin:
        restart: always
        build:
            context: ./docker/phpmyadmin
        container_name: ${APP_NAME}Phpmyadmin
        depends_on:
            - db
        ports:
            - 81:80
        networks:
            - web

networks:
    web:
        name: ${APP_NAME}Network
